dataset_name: MP-DocVQA
# CAMBIOS: Rutas relativas a la carpeta 'data' que acabamos de crear
imdb_dir: ./data/MP-DocVQA/imdb
images_dir: ./data/MP-DocVQA/images
layouts_dir: ./data/MP-DocVQA/layouts
page_retrieval: Concat