model:
  model: RAGVT5
  add_sep_token: False
  # CAMBIO: Usamos el modelo base de HuggingFace porque no tienes el checkpoint 'best.ckpt' de elopez
  model_weights: rubentito/vt5-base-spdocvqa

data:
  dataset: MP-DocVQA
  page_retrieval: Concat
  batch_size: 4 # Bajamos esto por si tu GPU es pequeña, luego lo subimos
  
retrieval:
  chunk_num: 20
  chunk_size: 60
  chunk_size_tol: 0.2
  overlap: 10
  include_surroundings: 0
  embed_model: BGE
  reranker_model: BGE
  # CAMBIO: Usamos el modelo público 'BAAI/bge-m3' en lugar de la ruta local rota
  embed_weights: ["BAAI/bge-m3"] 
  reranker_weights: BAAI/bge-reranker-v2-m3
  reorder_chunks: False
  rerank_filter_tresh: 0
  rerank_max_chunk_num: 10
  rerank_min_chunk_num: 1
  
runtime:
  # CAMBIO: Lightning suele darte la GPU 0. [8, 9] fallaría.
  visible_devices: [0] 
  save_folder: eval_results
  save_name_append: ["bge_m3_base"]
  val_size: 1.0
  log_wandb: True
  log_media_interval: 10
  return_scores_by_sample: True
  return_answers: True
  save_results: False
  save_continuously: True
  compute_stats: False
  compute_stats_examples: False
  n_stats_examples: 5