save_dir: save/
model_name: RAGPix2Struct
model_weights: google/pix2struct-docvqa-base
# CAMBIO: Rutas locales
cache_dir: ./models_cache
checkpoint_dir: ./checkpoints
device: cuda

training_parameters:
  lr: 1e-5
  batch_size: 4
  train_epochs: 1
  warmup_iterations: 500