save_dir: save/
model_name: RAGVT5
model_weights: rubentito/vt5-base-spdocvqa
# CAMBIO CLAVE: Usamos carpetas locales en lugar de la ruta de "elopez"
cache_dir: ./models_cache
checkpoint_dir: ./checkpoints
max_source_length: 512
device: cuda
data_parallel: False

training_parameters:
  lr: 2e-4
  batch_size: 4
  train_epochs: 4
  warmup_iterations: 1000

visual_module:
  model: 'dit' # 'vit' / 'dit'
  finetune: false
  # [cite_start]Este modelo coincide con el "Document Image Transformer" que menciona el paper [cite: 105]
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'

not_answerable_mlp:
  hidden_dim: 512
  num_layers: 2